### ISSUE TITLE
Document when `set_type` is optional and can auto-reflect

### ISSUE THREAD

**Issue by sunderipranata** [fast-jsonapi/fast_jsonapi#87]
## Expected Behavior
The serialization should be fine (even without set_type)
```
2.5.3 :027 > Serializer::Business::Pagination.new(b).serializable_hash
 => {:data=>{:id=>"5ec57f6c6ed1677a3381b12a", :type=>:business, :attributes=>{:category=>"asdf", :location=>"asdf", :thumbnail_url=>"asdf", :backers_count=>2, :id=>"5ec57f6c6ed1677a3381b12a"}}} 
```

## Actual Behavior
```
2.5.3 :007 > Serializer::Business::Pagination.new(b).serializable_hash
Traceback (most recent call last):
        4: from /usr/share/rvm/rubies/ruby-2.5.3/bin/irb:11:in `<main>'
        3: from (irb):7
        2: from /home/sunderipranata/.rvm/gems/ruby-2.5.3/gems/fast_jsonapi-1.7.2/lib/fast_jsonapi/object_serializer.rb:41:in `serializable_hash'
        1: from /home/sunderipranata/.rvm/gems/ruby-2.5.3/gems/fast_jsonapi-1.7.2/lib/fast_jsonapi/object_serializer.rb:52:in `hash_for_one_record'
NoMethodError (undefined method `to_sym' for nil:NilClass)
```

## Steps to Reproduce the Problem

  1. create a class which includes `FastJsonapi::ObjectSerializer`
  2. pass the model into the instance of class created at # 1
  3. if the class created at # 1 do not implement `set_type`, the script will return error

## Specifications

  - Version: 1.7.2
  - Ruby version: 2.5.3

**Comment by stas** [comment]
Hi there @sunderipranata 

I'm having a hard time understanding what is `Serializer::Business::Pagination`

Could you share with us the implementation please.

**Comment by sunderipranata** [comment]
here it is
```
module Serializer
  module Business
    class Pagination
      include FastJsonapi::ObjectSerializer

      set_id :id
      set_type :business_simple

      attributes :category, :location, :thumbnail_url
      attribute :backers_count do |object|
        object.backers.count
      end
    end
  end
end
```

**Comment by sunderipranata** [comment]
please consider this example:

```
2.7.0 :002 > 
2.7.0 :003 > class Anything
2.7.0 :004 >   attr_accessor :id, :a, :b
2.7.0 :005 > end
 => nil 
2.7.0 :006 > 
2.7.0 :007 > a=Anything.new
2.7.0 :008 > a
 => #<Anything:0x000055abf4f24608> 
2.7.0 :009 > 
2.7.0 :010 > class Serializer
2.7.0 :011 >   include FastJsonapi::ObjectSerializer
2.7.0 :012 >   set_id :id
2.7.0 :013 >   set_type :anything
2.7.0 :014 >   
2.7.0 :015 >   attributes :a, :b
2.7.0 :016 > end
 => [:a, :b] 
2.7.0 :017 > 
2.7.0 :018 > Serializer.new(a).serializable_hash
 => {:data=>{:id=>nil, :type=>:anything, :attributes=>{:a=>nil, :b=>nil}}} 
2.7.0 :019 > Serializer.new(a).class.record_type
 => :anything 
2.7.0 :020 > 
2.7.0 :021 > 
2.7.0 :022 > class Serializer2
2.7.0 :023 >   include FastJsonapi::ObjectSerializer
2.7.0 :024 >   set_id :id
2.7.0 :025 >   
2.7.0 :026 >   attributes :a, :b
2.7.0 :027 > end
 => [:a, :b] 
2.7.0 :028 > 
2.7.0 :029 > Serializer2.new(a).serializable_hash
Traceback (most recent call last):
        6: from /usr/share/rvm/rubies/ruby-2.7.0/bin/irb:23:in `<main>'
        5: from /usr/share/rvm/rubies/ruby-2.7.0/bin/irb:23:in `load'
        4: from /usr/share/rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        3: from (irb):28
        2: from /home/sunderipranata/.rvm/gems/ruby-2.7.0/gems/fast_jsonapi-1.7.2/lib/fast_jsonapi/object_serializer.rb:41:in `serializable_hash'
        1: from /home/sunderipranata/.rvm/gems/ruby-2.7.0/gems/fast_jsonapi-1.7.2/lib/fast_jsonapi/object_serializer.rb:52:in `hash_for_one_record'
NoMethodError (undefined method `to_sym' for nil:NilClass)
2.7.0 :030 > Serializer2.new(a).class.record_type
 => nil 
```

the root cause is here:
https://github.com/fast-jsonapi/fast_jsonapi/blob/master/lib/fast_jsonapi/object_serializer.rb#L52

If the code didn't specify `set_type`, then the class' `record_type` will be nil and the code won't run
In the README, it was stated that type is optional.

please correct me if im wrong, is this the intended behaviour?

**Comment by stas** [comment]
@sunderipranata can we also get an example of what's the object you're trying to serialize please?

**Comment by sunderipranata** [comment]
sorry I deleted the previous comment and provide you with a more clean example

**Comment by stas** [comment]
@sunderipranata the library will try to figure the type based on the name of your serializer class. In your case, your serializer class is `Serializer` which is generally a pretty generic name. Try changing your serializer class into something like `AnythingSerializer`. Should work...

```
irb(main):001:1* class Anything
irb(main):002:1*   attr_accessor :id, :a, :b
irb(main):003:0> end
=> nil
irb(main):004:0> a=Anything.new
irb(main):005:1* class AnythingSerializer
irb(main):006:1*   include FastJsonapi::ObjectSerializer
irb(main):007:1*   set_id :id
irb(main):008:1*   attributes :a, :b
irb(main):009:0> end
=> [:a, :b]
irb(main):010:0> AnythingSerializer.new(a).serializable_hash
=> {:data=>{:id=>nil, :type=>:anything, :attributes=>{:a=>nil, :b=>nil}}}
irb(main):011:0> 
```

I don't think this is a bug, but more of a documentation problem and we should update it to reflect the _optional_ity of `set_type`.

Patches welcome! :upside_down_face:

**Comment by sunderipranata** [comment]
ah I see! Nice explanation! OK will try to document it on README soon. Thanks!

**Comment by sunderipranata** [comment]
Hi @stas here is the pull request: https://github.com/fast-jsonapi/fast_jsonapi/pull/88
thanks!

**Comment by stas** [comment]
Thanks @sunderipranata !

**Comment by LE-HU** [comment]
just saved my day working with JSONAPI::Serializer - same issue - make the file name correspond to the object serialized. 
Thanks!
